// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlLhnQ-OLOP3C7P39KqRramVdYVc65SSU',
    appId: '1:1082200220343:web:c92439343bb4afeb9ca332',
    messagingSenderId: '1082200220343',
    projectId: 'mysoreguide-3b51c',
    authDomain: 'mysoreguide-3b51c.firebaseapp.com',
    storageBucket: 'mysoreguide-3b51c.appspot.com',
    measurementId: 'G-N5SVZVX9T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFR50f9jnYP3ZlXrVm-aLZIcmrbp-PQSY',
    appId: '1:1082200220343:android:e1fe13a2017818129ca332',
    messagingSenderId: '1082200220343',
    projectId: 'mysoreguide-3b51c',
    storageBucket: 'mysoreguide-3b51c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuyEU5Tc_yel-vyC2yMTIkSWkWrQYcing',
    appId: '1:1082200220343:ios:988a63f7c46539949ca332',
    messagingSenderId: '1082200220343',
    projectId: 'mysoreguide-3b51c',
    storageBucket: 'mysoreguide-3b51c.appspot.com',
    iosClientId:
        '1082200220343-06u4nt7jhluhs6eu8ee6n1rv6i3pm4un.apps.googleusercontent.com',
    iosBundleId: 'com.example.touristguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuyEU5Tc_yel-vyC2yMTIkSWkWrQYcing',
    appId: '1:1082200220343:ios:988a63f7c46539949ca332',
    messagingSenderId: '1082200220343',
    projectId: 'mysoreguide-3b51c',
    storageBucket: 'mysoreguide-3b51c.appspot.com',
    iosClientId:
        '1082200220343-06u4nt7jhluhs6eu8ee6n1rv6i3pm4un.apps.googleusercontent.com',
    iosBundleId: 'com.example.touristguide',
  );
}
